# Generated by Django 4.1.5 on 2023-01-16 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="subcategory",
            new_name="category",
        ),
    ]
