# Generated by Django 4.1.5 on 2023-01-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_comment_company_productsite_productsize_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(related_name="products", to="shop.category"),
        ),
    ]
