# Generated by Django 4.1.5 on 2023-01-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsite",
            name="image",
            field=models.ImageField(null=True, upload_to="files/covers"),
        ),
    ]
