# Generated by Django 4.1.5 on 2023-01-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_productsite_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="content",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="productsite",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="productsite",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="productsite",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="productsite",
            name="updated",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="productsite",
            name="url",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
