# Generated by Django 4.1.5 on 2023-01-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_comment_content_alter_comment_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="url",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
