# Generated by Django 4.1.5 on 2023-01-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_alter_category_name_alter_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsite",
            name="image",
            field=models.ImageField(null=True, upload_to="shop/files/covers"),
        ),
    ]
