# Generated by Django 4.1.5 on 2023-01-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_alter_productsite_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsite",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
