# Generated by Django 4.1.5 on 2023-01-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_remove_productsite_image_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("updated", models.DateField(auto_now=True, null=True)),
                (
                    "category",
                    models.ManyToManyField(related_name="products", to="shop.category"),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.RemoveField(
            model_name="productsite",
            name="product",
        ),
        migrations.AddField(
            model_name="productsite",
            name="content",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                related_query_name="comment",
                to="shop.productsite",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="shop.productsite",
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddField(
            model_name="productsite",
            name="subcategory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                related_query_name="site",
                to="shop.subcategory",
            ),
            preserve_default=False,
        ),
    ]
