# Generated by Django 4.1.5 on 2023-01-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_subcategory_remove_productsite_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsite",
            name="productsize",
        ),
        migrations.AddField(
            model_name="productsize",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="shop.productsite",
            ),
            preserve_default=False,
        ),
    ]
