# Generated by Django 4.1.5 on 2023-02-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_productsite_productsize_productsize_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='updated',
        ),
        migrations.AddField(
            model_name='productsite',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sites', related_query_name='site', to='shop.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='files/covers/'),
        ),
    ]
